spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/techhub
    username: root
    password: 1234

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: '门户网站'
      paths-to-match: '/**'
      packages-to-scan: edu.neuq.techhub.controller.user
    - group: '管理后台'
      paths-to-match: '/**'
      packages-to-scan: edu.neuq.techhub.controller.admin

# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn