server:
  port: 9000
spring:
  profiles:
    active: dev
  application:
    name: techhub
  servlet:
    multipart:
      max-file-size: 10MB
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: on
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
